monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.usb-Apple_Inc._Studio_Display.*" }
    ]
    actions = {
      update-props = {
        api.alsa.headroom = 1024
      }
    }
  }
]
