monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink"
      }
    ]
    actions = {
      update-props = {
        node.software-dsp = [
          {
            filter.graph = {
              nodes = [
                { type = builtin label = bq_highpass  name = HPL control = { Freq =    50.0 Q = 0.7 } }
                { type = builtin label = bq_highpass  name = HPR control = { Freq =    50.0 Q = 0.7 } }
                { type = builtin label = bq_lowshelf  name = LSL control = { Freq =   150.0 Q = 0.7 Gain =  4.0 } }
                { type = builtin label = bq_lowshelf  name = LSR control = { Freq =   150.0 Q = 0.7 Gain =  4.0 } }
                { type = builtin label = bq_peaking   name = E1L control = { Freq =   700.0 Q = 1.4 Gain = -7.0 } }
                { type = builtin label = bq_peaking   name = E1R control = { Freq =   700.0 Q = 1.4 Gain = -7.0 } }
                { type = builtin label = bq_peaking   name = E2L control = { Freq =  1500.0 Q = 1.2 Gain = -5.0 } }
                { type = builtin label = bq_peaking   name = E2R control = { Freq =  1500.0 Q = 1.2 Gain = -5.0 } }
                { type = builtin label = bq_peaking   name = E3L control = { Freq =  8000.0 Q = 1.0 Gain =  3.0 } }
                { type = builtin label = bq_peaking   name = E3R control = { Freq =  8000.0 Q = 1.0 Gain =  3.0 } }
                { type = builtin label = bq_highshelf name = E4L control = { Freq = 12000.0 Q = 0.7 Gain =  4.0 } }
                { type = builtin label = bq_highshelf name = E4R control = { Freq = 12000.0 Q = 0.7 Gain =  4.0 } }
              ]
              links = [
                { output = "HPL:Out" input = "LSL:In" }
                { output = "LSL:Out" input = "E1L:In" }
                { output = "E1L:Out" input = "E2L:In" }
                { output = "E2L:Out" input = "E3L:In" }
                { output = "E3L:Out" input = "E4L:In" }
                { output = "HPR:Out" input = "LSR:In" }
                { output = "LSR:Out" input = "E1R:In" }
                { output = "E1R:Out" input = "E2R:In" }
                { output = "E2R:Out" input = "E3R:In" }
                { output = "E3R:Out" input = "E4R:In" }
              ]
              inputs  = [ "HPL:In"  "HPR:In"  ]
              outputs = [ "E4L:Out" "E4R:Out" ]
            }
            capture.props = {
              audio.position = [ FL FR ]
            }
            playback.props = {
              audio.position = [ FL FR ]
            }
          }
        ]
      }
    }
  }
]
