# Arch Linux boot entry
# To install: copy to /boot/loader/entries/
title   Arch Linux (linux)
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options cryptdevice=PARTUUID=19591aeb-64e5-4f08-a2b8-10efb42d7ae0:root root=/dev/mapper/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs quiet loglevel=3 rd.systemd.show_status=auto rd.plymouth=0
